export const theme = {
  colors: {
    Razzmatazz: '#E10856',
    White: '#fff',
    bgColorGradient: '#23293E, #1D1D1D',
    TextColor: '#fff',
    TextTitleColor: '#0FEFFD',
    footerBgColor: '#262626',
    FooterTextColor: '#636366',
    PaginationColor: ' #333333',
  },

  pixelsSize: {
    None: 0,
    NinePixels: '9px',
    lineHeight: '2px',
    VerySmallSize: '10px',
    ExtraExtraSmallSize: '14px',
    ExtraSmallSize: '15px',
    backText: '18px',
    labelText: '16px',
    TextArt: '24px',
    SmallSize: '20px',
    mediumSize: '32px',
    LargeSize: '48px',
    FooterWidth: '99%',
    FooterWidthSM: '95%',
    TextLineHeightLargeSize: '64px',
    TextLargeSize: '56px',
    ExtraLargeSize: '53px',
    ExtraExtraSize: '80px',
    VeryLargeSize: '460px',
    FullSize: '100%',
    borderRadius: '8px',
    NavMargin: '0 20px',
    footerPadding: '16px 0',
    maxWidth: '150px',
    BoxShadow: '0 40px 40px',
    ExtraRadius: '40px',
    ArtMobileHeight: '350px',
    ArtWebHeight: '850px',
    LogoHeight: '360px',
    TextTopRightPadding: '4px 8px',
  },

  fontWeight: {
    small: '100',
    large: '300',
    extraLarge: '500',
  },
}
